version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://bun.sh/install | bash
      - export BUN_INSTALL="$HOME/.bun"
      - export PATH="$BUN_INSTALL/bin:$PATH"
      - echo "Bun version:" && bun --version
      - cd client && bun install && cd ..
      - cd api && bun install && cd ..
  build:
    commands:
      - echo "Building client..."
      - cd client
      - bun run build
      - zip -r ../client.zip build || echo "No client build output"
      - cd ..
      
      - echo "Building API..."
      - cd api
      - bun run build
      - zip -r ../api.zip build || echo "No API build output"
      - cd ..
  post_build:
    commands:
      - echo "Build done. Listing files:"
      - ls -la
artifacts:
  files:
    - client.zip
    - api.zip
