version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing Bun"
      - curl -fsSL https://bun.sh/install | bash
      - export BUN_INSTALL="$HOME/.bun"
      - export PATH="$BUN_INSTALL/bin:$PATH"
      - echo "Bun version:" && bun --version

  pre_build:
    commands:
      - echo "Installing dependencies"
      - cd client
      - bun install

  build:
    commands:
      - echo "Building app"
      - bun run build
      - cd ..

  post_build:
    commands:
      - echo "Zipping artifacts"
      - zip -r client-bundle.zip client/build appspec.yml scripts/

artifacts:
  files:
    - client-bundle.zip
  discard-paths: yes