version: 0.2

phases:
  install:
    commands:
      - echo "Installing Bun runtime..."
      - curl -fsSL https://bun.sh/install | bash
      - export BUN_INSTALL="$HOME/.bun"
      - export PATH="$BUN_INSTALL/bin:$PATH"
      - echo "Bun version:" && bun --version
      - cd client && bun install && cd ..

  build:
    commands:
      - echo "Building client..."
      - cd client
      - bun run build
      - cd ..

  post_build:
    commands:
      - echo "Packaging build..."
      - mkdir -p bundle/client
      - cp -r client/build/* bundle/client/
      - cp appspec.yml bundle/
      - cp -r scripts bundle/
      - cd bundle
      - zip -r ../client.zip ./
      - cd ..
      - echo "client.zip ready for deployment"

artifacts:
  files:
    - client.zip